version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL_IMAGE=${REACT_APP_API_URL_IMAGE}
      - REACT_APP_API_URL_RECOGNITION=${REACT_APP_API_URL_RECOGNITION}
    command:
      - npm yarn start --host 0.0.0.0 --port 3000
    volumes:
      - .:/repository
    tty: true