const FETCH_ALL_DETECTION: string = "FETCH_ALL_DETECTION";
const DELETE_ONE_DETECTION_BY_ID: string = "DELETE_ONE_DETECTION_BY_ID";
const FETCH_ALL_IMAGE: string = "FETCH_ALL_IMAGE";
const UPLOAD_MANY_IMAGE: string = "UPLOAD_MANY_IMAGE";
const DETECT_MANY_IMAGE: string = "DETECT_MANY_IMAGE";

export {
  FETCH_ALL_IMAGE,
  UPLOAD_MANY_IMAGE,
  FETCH_ALL_DETECTION,
  DELETE_ONE_DETECTION_BY_ID,
  DETECT_MANY_IMAGE
};