const FETCH_ALL_DETECTION: string = "FETCH_ALL_DETECTION";
const DELETE_ONE_DETECTION_BY_ID: string = "DELETE_ONE_DETECTION_BY_ID";
const FETCH_ALL_IMAGE: string = "FETCH_ALL_IMAGE";
const UPLOAD_ONE_IMAGE: string = "UPLOAD_ONE_IMAGE";
const DETECT_ONE_IMAGE: string = "DETECT_ONE_IMAGE";

export {
  FETCH_ALL_IMAGE,
  UPLOAD_ONE_IMAGE,
  FETCH_ALL_DETECTION,
  DELETE_ONE_DETECTION_BY_ID,
  DETECT_ONE_IMAGE
};